### ISSUE TITLE
Remove printStackTrace (log.error(e, e)) if folder not found in configuration validation.

### ISSUE THREAD

**Issue by pdp10** [pdp10/AstroJournal#46]
Reporting this as an error is sufficient.
Also, the message is not very accurate. 

Exception:
```
Impossible to copy the HeaderFooterFolder into the user AJFilesLocation. Do you have write permission?
java.io.FileNotFoundException: Source 'TEST\latex_header_footer' does not exist
	at org.apache.commons.io.FileUtils.copyDirectory(FileUtils.java:1368) ~[astrojournal-1.1.0-jar-with-dependencies.jar:?]
	at org.apache.commons.io.FileUtils.copyDirectory(FileUtils.java:1261) ~[astrojournal-1.1.0-jar-with-dependencies.jar:?]
	at org.astrojournal.configuration.ajconfiguration.AJConfigurationUtils.prepareAJHeaderFooter(AJConfigurationUtils.java:338) [astrojournal-1.1.0-jar-with-dependencies.jar:?]
	at org.astrojournal.configuration.ajconfiguration.AJConfigurationUtils.prepareFolders(AJConfigurationUtils.java:302) [astrojournal-1.1.0-jar-with-dependencies.jar:?]
	at org.astrojournal.configuration.ajconfiguration.PreferencesDialog.actionPerformed(PreferencesDialog.java:373) [astrojournal-1.1.0-jar-with-dependencies.jar:?]
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source) [?:1.8.0_66]
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source) [?:1.8.0_66]
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source) [?:1.8.0_66]
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source) [?:1.8.0_66]
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source) [?:1.8.0_66]
	at java.awt.Component.processMouseEvent(Unknown Source) [?:1.8.0_66]
	at javax.swing.JComponent.processMouseEvent(Unknown Source) [?:1.8.0_66]
	at java.awt.Component.processEvent(Unknown Source) [?:1.8.0_66]
	at java.awt.Container.processEvent(Unknown Source) [?:1.8.0_66]
	at java.awt.Component.dispatchEventImpl(Unknown Source) [?:1.8.0_66]
	at java.awt.Container.dispatchEventImpl(Unknown Source) [?:1.8.0_66]
	at java.awt.Component.dispatchEvent(Unknown Source) [?:1.8.0_66]
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source) [?:1.8.0_66]
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source) [?:1.8.0_66]
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source) [?:1.8.0_66]
	at java.awt.Container.dispatchEventImpl(Unknown Source) [?:1.8.0_66]
	at java.awt.Window.dispatchEventImpl(Unknown Source) [?:1.8.0_66]
	at java.awt.Component.dispatchEvent(Unknown Source) [?:1.8.0_66]
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source) [?:1.8.0_66]
	at java.awt.EventQueue.access$500(Unknown Source) [?:1.8.0_66]
	at java.awt.EventQueue$3.run(Unknown Source) [?:1.8.0_66]
	at java.awt.EventQueue$3.run(Unknown Source) [?:1.8.0_66]
	at java.security.AccessController.doPrivileged(Native Method) [?:1.8.0_66]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source) [?:1.8.0_66]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source) [?:1.8.0_66]
	at java.awt.EventQueue$4.run(Unknown Source) [?:1.8.0_66]
	at java.awt.EventQueue$4.run(Unknown Source) [?:1.8.0_66]
	at java.security.AccessController.doPrivileged(Native Method) [?:1.8.0_66]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source) [?:1.8.0_66]
	at java.awt.EventQueue.dispatchEvent(Unknown Source) [?:1.8.0_66]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source) [?:1.8.0_66]
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source) [?:1.8.0_66]
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source) [?:1.8.0_66]
	at java.awt.WaitDispatchSupport$2.run(Unknown Source) [?:1.8.0_66]
	at java.awt.WaitDispatchSupport$4.run(Unknown Source) [?:1.8.0_66]
	at java.awt.WaitDispatchSupport$4.run(Unknown Source) [?:1.8.0_66]
	at java.security.AccessController.doPrivileged(Native Method) [?:1.8.0_66]
	at java.awt.WaitDispatchSupport.enter(Unknown Source) [?:1.8.0_66]
	at java.awt.Dialog.show(Unknown Source) [?:1.8.0_66]
	at java.awt.Component.show(Unknown Source) [?:1.8.0_66]
	at java.awt.Component.setVisible(Unknown Source) [?:1.8.0_66]
	at java.awt.Window.setVisible(Unknown Source) [?:1.8.0_66]
	at java.awt.Dialog.setVisible(Unknown Source) [?:1.8.0_66]
	at org.astrojournal.configuration.ajconfiguration.PreferencesDialog.initComponents(PreferencesDialog.java:267) [astrojournal-1.1.0-jar-with-dependencies.jar:?]
	at org.astrojournal.configuration.ajconfiguration.PreferencesDialog.<init>(PreferencesDialog.java:173) [astrojournal-1.1.0-jar-with-dependencies.jar:?]
	at org.astrojournal.gui.AJMainGUI.configure(AJMainGUI.java:172) [astrojournal-1.1.0-jar-with-dependencies.jar:?]
	at org.astrojournal.gui.menu.AJMenuBar.actionPerformed(AJMenuBar.java:192) [astrojournal-1.1.0-jar-with-dependencies.jar:?]
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source) [?:1.8.0_66]
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source) [?:1.8.0_66]
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source) [?:1.8.0_66]
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source) [?:1.8.0_66]
	at javax.swing.AbstractButton.doClick(Unknown Source) [?:1.8.0_66]
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(Unknown Source) [?:1.8.0_66]
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(Unknown Source) [?:1.8.0_66]
	at java.awt.Component.processMouseEvent(Unknown Source) [?:1.8.0_66]
	at javax.swing.JComponent.processMouseEvent(Unknown Source) [?:1.8.0_66]
	at java.awt.Component.processEvent(Unknown Source) [?:1.8.0_66]
	at java.awt.Container.processEvent(Unknown Source) [?:1.8.0_66]
	at java.awt.Component.dispatchEventImpl(Unknown Source) [?:1.8.0_66]
	at java.awt.Container.dispatchEventImpl(Unknown Source) [?:1.8.0_66]
	at java.awt.Component.dispatchEvent(Unknown Source) [?:1.8.0_66]
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source) [?:1.8.0_66]
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source) [?:1.8.0_66]
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source) [?:1.8.0_66]
	at java.awt.Container.dispatchEventImpl(Unknown Source) [?:1.8.0_66]
	at java.awt.Window.dispatchEventImpl(Unknown Source) [?:1.8.0_66]
	at java.awt.Component.dispatchEvent(Unknown Source) [?:1.8.0_66]
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source) [?:1.8.0_66]
	at java.awt.EventQueue.access$500(Unknown Source) [?:1.8.0_66]
	at java.awt.EventQueue$3.run(Unknown Source) [?:1.8.0_66]
	at java.awt.EventQueue$3.run(Unknown Source) [?:1.8.0_66]
	at java.security.AccessController.doPrivileged(Native Method) [?:1.8.0_66]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source) [?:1.8.0_66]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source) [?:1.8.0_66]
	at java.awt.EventQueue$4.run(Unknown Source) [?:1.8.0_66]
	at java.awt.EventQueue$4.run(Unknown Source) [?:1.8.0_66]
	at java.security.AccessController.doPrivileged(Native Method) [?:1.8.0_66]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source) [?:1.8.0_66]
	at java.awt.EventQueue.dispatchEvent(Unknown Source) [?:1.8.0_66]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source) [?:1.8.0_66]
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source) [?:1.8.0_66]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source) [?:1.8.0_66]
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source) [?:1.8.0_66]
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source) [?:1.8.0_66]
	at java.awt.EventDispatchThread.run(Unknown Source) [?:1.8.0_66]
```

**Comment by pdp10** [comment]
Now the message is: 
```
Initialisation of folder containing headers and footers failed. Please, check your preferences.
```

**Comment by pdp10** [comment]
Approved.
